#!/usr/bin/python3

# SPDX-FileCopyrightText: 2026 Ryoya Sato
# SPDX-License-Identifier: BSD-3-Clause

import sys
sum = 0

def tonum(s):
    try:
        return  int(s)

    except:
        return  float(s)

for lines in sys.stdin:
    sum += tonum(lines)

print(sum)
